### ISSUE TITLE
Directory error

### ISSUE THREAD

**Issue by theMackabu** [wexond/browser-base#230] opened 2019-07-10 20:26 UTC
![Screen Shot 2019-07-10 at 1 26 36 PM](https://user-images.githubusercontent.com/32078755/61002433-62943980-a316-11e9-8643-e01038cc2701.png)

**Comment by xnerhu** [comment] 2019-07-10 21:55
Duplicate of [#217](https://github.com/wexond/wexond/issues/217).

**Closed as completed by xnerhu** 2019-07-10 21:55 UTC
Labels: duplicate
