### ISSUE TITLE
Signing with gmail account using google services not working (error)

### ISSUE THREAD

**Issue by MrLuxuri** [wexond/browser-base#550] opened 2021-02-12 19:55 UTC
Whenever i try to login somewhere with google services for example gmail, 
it gives me an error saying: 

> This browser or app may not be secure. Learn more
> Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.

**Comment by sentialx** [comment] 2021-02-12 20:03
Duplicate of #424

**Closed as completed by sentialx** 2021-02-12 20:03 UTC
