### ISSUE TITLE
Tab Bar disappears after 2 searches or open tag groups

### ISSUE THREAD

**Issue by theMackabu** [wexond/browser-base#166] opened 2019-04-11 18:38 UTC
Steps to reproduce

1. Open tab groups
2. Open 2 tabs
![Screen Shot 2019-04-11 at 11 37 08 AM](https://user-images.githubusercontent.com/32078755/55982649-37824700-5c4e-11e9-9341-601eeab304ec.png)

**Comment by sentialx** [comment] 2019-04-11 18:41
This has been fixed, and it's a duplicate of #163

**Closed as completed** 2019-04-11 18:40 UTC
Labels: bug, duplicate, fixed in upstream
