### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by davidraywilson** [wexond/browser-base#310] opened 2019-08-29 15:40 UTC
The site permissions seem to still be having some issues. When going to Google to search, it repeatedly asks for my location. When going to Hulu it asks for my location but it can't find it. Thanks!

 - Operating System: Mac OS
 - Wexond version: 3.0.1

**Comment by sentialx** [comment] 2019-09-01 14:23
Duplicate of #213

**Closed as completed by sentialx** 2019-09-01 14:23 UTC
